In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf

- Tensorflow is an open source machine learning platform that is owned and maintained by google and is one of the largest open source learning liraries in the world.
- It can be usedto build models that can do :
  - image classification
  - data clustering
  - Regression
  - Reinforcement learning
  - Text classification
  - Natural Language Processing
  - Classification


- It works(on a lower level) using two main components Graphs and sessions
- Tensorflow works bu building a graph of defined computations.Nothing is computed or stored in this graph.It is  simply a way of defining the operatipns that have being written in code.
- A tensorflow session allows parts of a graph to be executed.It allows memory and resources and handles the execution of the operations and computations we've defined
- In some cases we need to run a session to be able to execute parts of the graph we've created earlier

In [5]:
 print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\ADMIN\\AppData\\Roaming\\Python\\Python312\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


- A **tensor** is a generalization of vectors and matrices to potentially higher dimensions.Internally,Tensorflow represents tensors as n-dimensional arrays of base datatypes
- They are the fundamental aspect of Tensorflow.They are the main objects that are passed around and manipulated throughout the program.
- Each tensor represents a partialy defined compuation and will eventually produce a value.
-Tensorflow  programs work by building a raph of Tensor objects taht dtails how tensors are related.Running different parts of the graph allow results to be generated.
- Each tensor has a datatype and a shape(dimenion of the data)


In [6]:
#Creating a tensor 
string=tf.Variable("This is a string",tf.string)
integer=tf.Variable(1234,tf.int16)
floating=tf.Variable(23425.8990,tf.float64)

In [7]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>

**Rank/Degree of tesors**
- This means the number of dimension involved in the tensor.What we've created above are tensors f degree/rank 0 also known as scalar.

In [19]:
#Tensors of higher degrees/rank
rank1_tensor=tf.Variable(['Test','list'],tf.string)#when we have an arrya or list it's absolutely a rank 1 co list or array can store more tthan 1 item even when in one dimension
rank2_tensor=tf.Variable([['test','okay','yes'],['Test','yes','okey']],tf.string)
print(rank1_tensor)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'Test', b'list'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'test', b'okay', b'yes'],
       [b'Test', b'yes', b'okey']], dtype=object)>


In [20]:
#to determine rank of atensor
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


**Shape of tensor**
- Shape of a tensor is amount of elements that exist in each dimension
- Sometimes it's knwn sometimes it's not known



In [ ]:
print(rank1_tensor.shape)#we have 2 items in row one and no other item coz there's no other row/dimesion
print(rank2_tensor.shape)#we have 2 rows and 3 columns thus it is 2 by 3 numpy array

(2,)
(2, 3)


- Number of elements in a tensor is the product of the sizes of all it's shapes.There are often many shapes thst have the same number of elements making it convinient to be able t cahnge the shape of the tensor 
- But note the number of elements i  the reshaped tensor must be equal to those in the original tensor

In [ ]:
tensor1=tf.ones([1,2,3])#this creates a shape [1,2,3] tensor full of ones
tensor1
#notice the extrasquare bracket which caters for the 1 

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tensor2=tf.reshape(tensor1,[2,3,1])#reshapes the existing tensor1 to the passed in shape
tensor2
#an array with 2 nested arrays and each array has 3 rows(lists) and 1 column(each list has this number of items)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tensor3=tf.reshape(tensor2,[3,-1])
#-1 tells the tensor to calculate the size if the dimesion in that place 
#thus this will reshape to [3,2] thus maintaining the number of elements
#we gonna have 3 lists and we ginna infer what thsi dimesion should e 
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

**Types of tensors**
- Variable 
- constant
- placeholder
- sparsetensor
- Apart from variable all the tensor types here are inmmutable ie they cannot be changed during execution

**Evaluating tensors**
- This is basically getting it's value.Since tensors,represents a partially compleye computation we will sometimes need to run what is called  session to evaluate a tensor
- There are many ways to achieve this but the simplest but note outdated using the tensor version 2.x is:

- with tf.Session() as sess:(creates a session using the defalut graph)
    - tensor.eval()
- In the code the tensor variable to be  evaluated is stored in the default graph.
- We haven't defined a graph yet
- This the outdated way and now yu can basically evaluate using normal means eg print()